name: mikepspiegel
on:
  pull_request:

permissions:
  contents: read

jobs:
  build-mikespiegel:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
      DOCUSAURUS_SSR_CONCURRENCY: 5
      

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.7

      - name: use node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: mikespiegel dependencies install
        run: npm ci

      - name: build mikespiegel
        run: npm run build
